#!/bin/env bash

sudo pacman -S --needed --noconfirm git
git config --global core.excludesfile ~/.gitignore_global

touch ~/.gitignore_global

echo "~/.gitignore_global is the global gitignore file."
