#!/bin/env bash

sudo pacman -S --noconfirm --needed hyprland hyprpaper hyprlock hypridle hyprsunset kitty waybar wofi wl-clipboard hyprshot hyprpicker polkit-gnome uwsm xdg-desktop-portal-gtk xdg-desktop-portal-hyprland

systemctl --user enable --now ssh-agent.socket
systemctl --user enable --now waybar.service
systemctl --user enable --now cliphist.service
systemctl --user enable --now ssh-agent.socket
systemctl --user enable --now hyprpaper.service
systemctl --user enable --now hypridle.service

# sudo pacman -S --noconfirm --needed cliphist fzf gimp vlc vlc-plugins-all firefox
