#!/usr/bin/env bash

sudo pacman --noconfirm --needed -S powertop   # see what's consuming power
sudo pacman --noconfirm --needed -S tlp        # granular power management

sudo systemctl enable --now tlp                # enable tlp

# save changes to disks from ram every 15sec instead of 5sec (saves power)
# that's virtual memory writeback ;)
echo "vm.dirty_writeback_centisecs = 1500" | sudo tee /etc/sysctl.d/99-powersave.conf
sudo sysctl -p /etc/sysctl.d/99-powersave.conf

# use envycontrol to use only integrated gpu instead of nvidia
yay --noconfirm --needed -S envycontrol
if envycontrol --query | grep -q "integrated"; then
  sudo envycontrol -s integrated
fi

# to start a program with nvidia graphics card
# allows to do prime-run cmd to run that command using nvidia graphics card

# sudo pacman -S nvidia-prime
