# preload = /home/shyam/wp/WALLPAPERS_NATURE/Wallpaper 1080p (85).jpg
# preload = /home/shyam/wp/WALLPAPERS_NATURE/Wallpaper 1080p (48).jpg
#
# wallpaper = , /home/shyam/wp/WALLPAPERS_NATURE/Wallpaper 1080p (48).jpg

wallpaper {
  monitor =
  # path = /home/shyam/wp/WALLPAPERS_NATURE/Wallpaper 1080p (48).jpg
  # path = /home/shyam/Pictures/DSC02905.jpg
  # path = /home/shyam/Pictures/Wallpapers/mpv-shot0001.jpg
  # path = /home/shyam/Downloads/wallpapers/my-neighbor-totoro-hayao-miyazaki.jpg
  path = /home/shyam/Pictures/shots/malleswaram/19460411/DSC04738.JPG
  fit_mode = cover
}

