profile {
  time = 7:30
  identity = true
}

profile {
  time = 19:30
  temperature = 5000
}

profile {
  time = 20:30
  temperature = 4000
}

profile {
  time = 21:00
  temperature = 3500
}

profile {
  time = 22:00
  temperature = 3000
}
