# Fonts
font_family family="Lilex"
font_size 14
modify_font cell_height 120%
modify_font cell_width 100%
modify_font underline_position 4
modify_font underline_thickness 150%

# No cursor blinking
cursor_blink_interval 0

# Mouse
mouse_hide_wait 10.0
url_style double

# tab bar
tab_bar_edge top
tab_bar_style powerline

enable_audio_bell no

# background
background_opacity 0.85
background #111111
background_blur 8

